In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("cumulative.csv",encoding='utf-8',nrows=9564)
print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()
df.info()
df.describe()
df.shape

print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

print("Column names:\n")
for column in df.columns:
    print(column)


print("--------TO FIND EMPTY COLUMNS--------")
emp_col = []
for column in df.columns:
    if df[column].isnull().all():
        emp_col.append(column)
print("Completely empty columns:")
print(emp_col)

print("Number of completely empty columns:", len(emp_col))



print("-----MISSING VALUES-----")
missing_values = df.isnull().sum()
print(missing_values)


print("------MISSING VALUES PERCENTAGE-------")
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage.round(2))



print("------MISSING REPORT------")
missing_report = pd.DataFrame()
missing_report["Column"] = df.columns
missing_report["Missing Values"] = df.isnull().sum().values
missing_report["Missing Percentage"] = (
    df.isnull().sum().values / len(df) * 100
).round(2)
print(missing_report)



missing_report = missing_report.sort_values(
    "Missing Percentage",
    ascending=False
)
print(missing_report)



print("-----DUPLICATE ROWS------")
dupl_rows = df.duplicated().sum()
print("Number of duplicate rows:", dupl_rows)


if dupl_rows > 0:
    df[df.duplicated()]
else:
    print("No duplicate rows found.")


dupl_kepoi = df["kepoi_name"].duplicated().sum()
print("Duplicate KOI names:", dupl_kepoi)

df[df["kepoi_name"].duplicated(keep=False)][
    ["kepoi_name", "koi_disposition"]
].head(20)

print(df["koi_disposition"].value_counts(dropna=False))





print("-----Numerical columns-----")
num_columns = df.select_dtypes(
    include=np.number
).columns
print("Number of numerical columns:", len(num_columns))
print("\nNumerical columns:")
for column in num_columns:
    print(column)



print("-------Catergorical columns-------")
cate_columns = df.select_dtypes(
    include="object"
).columns
print("Number of categorical columns:", len(cate_columns))
print("\nCategorical columns:")
for column in cate_columns:
    print(column)


print("-----check infinity values-------------")
infi_values = np.isinf(df[num_columns]).sum()
print("Columns with infinite values:")
print(infi_values[infi_values > 0])
print()


print("-----Check negative values-----------")
neg_values = (df[num_columns] < 0).sum()
print("Columns with negative values:")
print(neg_values[neg_values > 0])
print()
















print("--Datasets--")
df_clean = df.copy()
print("Original dataset:", df.shape)
print("Cleaning dataset:", df_clean.shape)
print()


print("--New dataset--")
df_clean = df_clean.drop(columns=emp_col)
print("Removed empty columns:", len(emp_col))
print("New dataset shape:", df_clean.shape)
print()



print("--column details--")
print("Original columns:", len(df.columns))
print("Cleaned columns:", len(df_clean.columns))
print()



print("--Remaining complete empty col--")
print("Remaining completely empty columns:")
print(
    df_clean.columns[
        df_clean.isnull().all()
    ].tolist()
)

for column in df_clean.columns:
    print(column, "→", df_clean[column].dtype)
print()




print("--ID for unique column--")
id_col = [
    "kepid",
    "kepoi_name",
    "kepler_name"
]
target_col = "koi_disposition"

print("ID columns:")
print(id_col)
print()
print("\nTarget column:")
print(target_col)
print()




print("-----------------------")
for column in id_col:
    if column in df_clean.columns:
        print(column, " found")
    else:
        print(column, " Not found")
print()



print("------------------------")
cate_columns = df_clean.select_dtypes(
    include="object"
).columns.tolist()

print("Categorical columns:")
for column in cate_columns:
    print("-", column)
print()



print("------------------------")
num_columns = df_clean.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical columns:")
for column in num_columns:
    print("-", column)
print()




print("-------------------------")
print("Target column:", target_col)
print("\nValues:")
print(df_clean[target_col].value_counts(dropna=False))
print()





print("------------------------------")
col_type = []

for col in df_clean.columns:
    if col in id_col:
        category = "ID"
    elif col == target_col:
        category = "Target"
    elif col in cate_columns:
        category = "Categorical"
    else:
        category = "Numerical"
    col_type.append(category)

col_clasfic = pd.DataFrame({
    "Column": df_clean.columns,
    "Data Type": df_clean.dtypes.astype(str).values,
    "Category": col_type
})
print(col_clasfic)
print()




print("-----------------------")
col_clasfic["Missing Values"] = (
    df_clean.isnull().sum().values
)
col_clasfic["Missing %"] = (
    df_clean.isnull().sum().values /
    len(df_clean) * 100
).round(2)
print(col_clasfic)
print()





print("----------High missing columns--------------")
high_mis = col_clasfic[
    col_clasfic["Missing %"] >= 50
]
print("Columns with 50% or more missing values:")
display(high_mis)
print()






print("-------------Low missing columns-----------")
low_mis = col_clasfic[
    (col_clasfic["Missing %"] > 0) &
    (col_clasfic["Missing %"] < 50)
]
print("Columns with less than 50% missing values:")
display(low_mis)
print()






print("----------------------------")
col_clasfic.to_csv(
    "column_classification.csv",
    index=False
)
print("Column classification saved successfully.")
print()
print()





# Creating data dictionary for the reference of our project
#Data dictionary separate csv file will provide

print("------Data dict-----------")
data_dic= pd.DataFrame()
data_dic["Column"] = df_clean.columns
data_dic["Data Type"] = df_clean.dtypes.astype(str).values
print(data_dic)
print()



print("------After catergory added in data dic-----------")
data_dic["Category"] = col_clasfic["Category"].values
print(data_dic)
print()



print("--------------------------------------------------------")
data_dic["Missing Values"] = df_clean.isnull().sum().values
data_dic["Missing %"] = (
    df_clean.isnull().sum().values / len(df_clean) * 100
).round(2)
print(data_dic)
print()




# Meanings or full form of the keplers column name in the given project
print("------------------------------------------------------------------")
kepler_meanings = {
    "kepid": "Kepler identification number",
    "kepoi_name": "Kepler Object of Interest name",
    "kepler_name": "Official Kepler name assigned to a confirmed planet",
    "koi_disposition": "Final classification/disposition of the object",
    "koi_period": "Orbital period of the candidate",
    "koi_period_err1": "Upper uncertainty of orbital period",
    "koi_period_err2": "Lower uncertainty of orbital period",
    "koi_time0bk": "Transit midpoint time",
    "koi_time0bk_err1": "Upper uncertainty of transit midpoint",
    "koi_time0bk_err2": "Lower uncertainty of transit midpoint",
    "koi_impact": "Impact parameter of the transit",
    "koi_depth": "Transit depth",
    "koi_prad": "Estimated planetary radius",
    "koi_teq": "Estimated equilibrium temperature",
    "koi_insol": "Estimated incident stellar flux",
    "koi_steff": "Effective temperature of the host star",
    "koi_slogg": "Surface gravity of the host star",
    "koi_srad": "Radius of the host star"
}

data_dic["Meaning"] = data_dic["Column"].map(
    kepler_meanings
)
print(data_dic)
print()





print("-----------------------------------------")
undocu = data_dic[
    data_dic["Meaning"].isnull()
]
print("Columns still needing documentation:")
print(undocu["Column"].tolist())
print()






print("------------------------------------------")
ml_role = []
for column in df_clean.columns:
    if column in id_col:
        role = "Do not use directly"
    elif column == target_col:
        role = "Target"
    else:
        role = "Potential feature"
    ml_role.append(role)
data_dic["ML Role"] = ml_role
print(data_dic)
print()





print("======================================")
data_dic.to_csv(
    "data_dictionary.csv",
    index=False
)
print("Data dictionary saved successfully!")
print()





print("---------Missing values----------")
mis_values = df_clean.isnull().sum()
print("Missing values in each column:")
print(mis_values[mis_values > 0])
print()






print("-----------Missing percentage----------")
mis_percent = (
    df_clean.isnull().sum() / len(df_clean) * 100
).round(2)
print("Missing percentage:")
print(mis_percent[mis_percent > 0])
print()




print("-----------------------------------------------")
missing_report = pd.DataFrame()
missing_report["Column"] = df_clean.columns
missing_report["Missing Values"] = [
    df_clean[column].isnull().sum()
    for column in df_clean.columns
]
missing_report["Missing %"] = [
    round(df_clean[column].isnull().mean() * 100, 2)
    for column in df_clean.columns
]
missing_report = missing_report[
    missing_report["Missing Values"] > 0
]
missing_report = missing_report.sort_values(
    "Missing %",
    ascending=False
)
display(missing_report)
print()






print("------------------------------------------")
missing_report = missing_report.merge(
    data_dic[
        ["Column", "Meaning", "Category"]
    ],
    on="Column",
    how="left"
)
display(missing_report)
print()






print("-----------Missing level and decision---------------")
def mis_lvl(percent):
    if percent < 30:
        return "Low"
    elif percent < 50:
        return "Medium"
    elif percent < 80:
        return "High"
    else:
        return "Very High"
        
missing_report["Missing Level"] = [
    mis_lvl(percent)
    for percent in missing_report["Missing %"]
]
display(missing_report)
print()





print("---------------------------------------------------------")
dec = []
for index, row in missing_report.iterrows():
    column = row["Column"]
    perc = row["Missing %"]
    catg = row["Category"]

    if perc >= 80:
        decision = "Remove column"
    elif catg == "Numerical":
        decision = "Fill median"
    elif catg == "Categorical":
        decision = "Fill mode"
    else:
        decision = "Review"
        
    dec.append(decision)

missing_report["Decision"] = dec
display(
    missing_report[
        [
            "Column",
            "Missing %",
            "Meaning",
            "Category",
            "Decision"
        ]
    ]
)
print()






print("---------Saving Missing value decision in a csv file------------")
missing_report.to_csv(
    "missing_val_decision.csv",
    index=False
)
print("Missing-value decisions saved successfully!")
print()





print("------Data cleaning--------")
col_to_rem = missing_report[
    missing_report["Decision"] == "Remove column"
]["Column"].tolist()
print("Columns to remove:")
print(col_to_rem)
print()





print("------Dropping column-----------")
df_clean = df_clean.drop(
    columns=col_to_rem
)
print("Columns removed:", len(col_to_rem))
print()







print("------------------------------------------")
num_col = df_clean.select_dtypes(
    include=np.number
).columns
for column in num_col:

    if df_clean[column].isnull().sum() > 0:
        median_val = df_clean[column].median()

        df_clean[column] = df_clean[column].fillna(
            median_val
        )
print("Numerical missing values filled.")
print()





print("-----------------------------------------")
categ_col = df_clean.select_dtypes(
    include="object"
).columns

for column in categ_col:

    if df_clean[column].isnull().sum() > 0:
        
        mode_val = df_clean[column].mode()[0]
        df_clean[column] = df_clean[column].fillna(
            mode_val
        )
print("Categorical missing values filled.")
print()




print("------checking remaining missing values-------")
rema_mis = df_clean.isnull().sum()
rema_mis = rema_mis[
    rema_mis > 0
]
print("Remaining missing values:")

if len(rema_mis) == 0:
    print("No missing values")
else:
    print(rema_mis)

print()
print()




print("-------Final comparision----------")
print("Original dataset:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print()

print("Cleaned dataset:")
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print()

print(
    "Total missing values after cleaning:",
    df_clean.isnull().sum().sum()
)
print()




print("-----Saving the cleaned dataset---------")
df_clean.to_csv(
    "Data_cleaned.csv",
    index=False
)
print("Cleaned dataset saved successfully!")
print()

print("-----------cleaning done---------------")
print()
print()






print("------------ OUTLIER FLAG----------------------")
outlier_columns = [
    "koi_period",
    "koi_duration",
    "koi_depth",
    "koi_prad",
    "koi_teq",
    "koi_insol",
    "koi_model_snr",
    "koi_steff",
    "koi_slogg",
    "koi_srad",
    "koi_kepmag"
]

outlier_report = []

for column in outlier_columns:
    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    flag_column = column + "_outlier"

    df_clean[flag_column] = (
        (df_clean[column] < lower_limit) |
        (df_clean[column] > upper_limit)
    ).astype(int)

    outlier_count = df_clean[flag_column].sum()

    outlier_report.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outlier Count": outlier_count
    })

outlier_report = pd.DataFrame(outlier_report)

flag_columns = [
    column + "_outlier"
    for column in outlier_columns
]

df_clean["outlier_flag"] = (
    df_clean[flag_columns].max(axis=1)
)

print("Outlier flagging completed.")
print()

print("Total rows:", len(df_clean))
print(
    "Rows containing at least one outlier:",
    df_clean["outlier_flag"].sum()
)

print("\nOutlier Report:")
display(outlier_report)
print()










print("-------------------- HOST STAR analyze using kepid----------------------")

unique_host_stars = df_clean["kepid"].nunique()

print("Total observations:", len(df_clean))
print("Unique host stars:", unique_host_stars)
print()

host_counts = (
    df_clean
    .groupby("kepid")
    .size()
    .reset_index(name="KOI_Count")
)
print("Host-star observation counts:")
display(host_counts.head(10))

multi_observation_hosts = host_counts[
    host_counts["KOI_Count"] > 1
]

print(
    "Host stars with more than one observation:",
    len(multi_observation_hosts)
)

host_summary = (
    df_clean
    .groupby("kepid")
    .agg(
        KOI_Count=("kepoi_name", "count"),

        Confirmed=("koi_disposition",
                   lambda x: (x == "CONFIRMED").sum()),

        Candidate=("koi_disposition",
                   lambda x: (x == "CANDIDATE").sum()),

        False_Positive=("koi_disposition",
                        lambda x: (x == "FALSE POSITIVE").sum())
    )
    .reset_index()
)
print("\nDetailed host-star summary:")
display(host_summary.head(10))

largest_systems = host_summary.sort_values(
    "KOI_Count",
    ascending=False
)
print("\nHost stars with highest number of observations:")
display(largest_systems.head(10))
print()










print("------------------GROUP DATA BY HOST STAR------------------------")

from sklearn.model_selection import GroupShuffleSplit

target_column = "koi_disposition"

group_column = "kepid"

group_split = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_index, test_index = next(
    group_split.split(
        df_clean,
        df_clean[target_column],
        groups=df_clean[group_column]
    )
)
train_df = df_clean.iloc[train_index].copy()

test_df = df_clean.iloc[test_index].copy()

print("Host-star based splitting completed.")
print()

print("Original dataset:")
print("Rows:", len(df_clean))
print()

print("Training dataset:")
print("Rows:", len(train_df))
print("Unique host stars:", train_df["kepid"].nunique())
print()

print("Testing dataset:")
print("Rows:", len(test_df))
print("Unique host stars:", test_df["kepid"].nunique())
print()

train_hosts = set(train_df["kepid"])
test_hosts = set(test_df["kepid"])

common_hosts = train_hosts.intersection(test_hosts)

print("Host stars present in both datasets:",
      len(common_hosts))

if len(common_hosts) == 0:
    print("PASS: No host star is shared between train and test.")
else:
    print("WARNING: Host-star overlap detected.")








print("--------------- FINAL PREPARED DATASET_-----------------------")


print("FINAL DATASET ")

print("\n1. DATASET SHAPE")
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])


print("\n2. MISSING VALUES")

missing_total = df_clean.isnull().sum().sum()

print("Total missing values:", missing_total)

if missing_total == 0:
    print("PASS: No missing values found.")
else:
    print("WARNING: Missing values still exist.")


print("\n3. DUPLICATE ROWS")

duplicate_rows = df_clean.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

if duplicate_rows == 0:
    print("PASS: No duplicate rows found.")
else:
    print("WARNING: Duplicate rows found.")


print("\n4. INFINITE VALUES")

numeric_columns = df_clean.select_dtypes(
    include=np.number
).columns

infinite_values = np.isinf(
    df_clean[numeric_columns]
).sum().sum()

print("Infinite values:", infinite_values)

if infinite_values == 0:
    print("PASS: No infinite values found.")
else:
    print("WARNING: Infinite values found.")



print("\n5. TARGET DISTRIBUTION")

print(
    df_clean["koi_disposition"].value_counts()
)



print("\n6. OUTLIER INFORMATION")
print(
    "Rows with at least one flagged outlier:",
    df_clean["outlier_flag"].sum()
)



print("\n7. HOST-STAR SPLIT VALIDATION")

train_hosts = set(train_df["kepid"])
test_hosts = set(test_df["kepid"])

common_hosts = train_hosts.intersection(test_hosts)
print(
    "Common host stars between train and test:",
    len(common_hosts)
)
if len(common_hosts) == 0:
    print("PASS: Train and test host stars do not overlap.")
else:
    print("WARNING: Host-star overlap detected.")

print()

print("-------------------------------------------------------------")

if (
    missing_total == 0
    and duplicate_rows == 0
    and infinite_values == 0
    and len(common_hosts) == 0
):
    print("FINAL VALIDATION: PASSED")
else:
    print("FINAL VALIDATION: CHECK WARNING")

print("---------------------------------------------------")
print()








#---------------------READ BELOW----------------------------
# Only for our team to download and save the dataset 
# please remove unnecessary wordings in the below code if you used in your code

print("---------- SHARING - PREPARED DATA---------------")


import os

#make sure to have a folder in these names to save .
os.makedirs("prepared_data", exist_ok=True)
os.makedirs("reports", exist_ok=True)


# 1. Save complete prepared dataset

df_clean.to_csv(
    "prepared_data.csv",
    index=False
)


# 2. Save training dataset

train_df.to_csv(
    "kepler_train_by_host.csv",
    index=False
)

# 3. Save testing dataset

test_df.to_csv(
    "kepler_test_by_host.csv",
    index=False
)

# 4. Save host-star summary

host_summary.to_csv(
    "rep_host_star_summary.csv",
    index=False
)


# 5. Save outlier report

outlier_report.to_csv(
    "rep_outlier_report.csv",
    index=False
)


# 6. Create final validation summary dataset

validation_summary = pd.DataFrame({
    "Check": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows",
        "Infinite Values",
        "Unique Host Stars",
        "Flagged Outlier Rows",
        "Training Rows",
        "Testing Rows",
        "Common Train-Test Host Stars"
    ],

    "Result": [
        df_clean.shape[0],
        df_clean.shape[1],
        missing_total,
        duplicate_rows,
        infinite_values,
        df_clean["kepid"].nunique(),
        df_clean["outlier_flag"].sum(),
        len(train_df),
        len(test_df),
        len(common_hosts)
    ]
})

validation_summary.to_csv(
    "rep_final_validation.csv",
    index=False
)
print()
print()




print("-------------ALL FILES EXPORTED SUCCESSFULLY---------------------")


print("\nPrepared Data Files:")
print("1. prepared_data.csv")
print("2. kepler_train_by_host.csv")
print("3. kepler_test_by_host.csv")
print()

print("\nReport Files:")
print("4. rep_host_star_summary.csv")
print("5. rep_outlier_report.csv")
print("6. rep_final_validation.csv")
print()

print("\nMember 1 data preparation work is completed.")

Dataset loaded successfully!
Number of rows: 9564
Number of columns: 50
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              9564 non-null   int64
 1   kepid              9564 non-null   int64
 2   kepoi_name         9564 non-null   object
 3   kepler_name        2294 non-null   object
 4   koi_disposition    9564 non-null   object
 5   koi_pdisposition   9564 non-null   object
 6   koi_score          8054 non-null   float64
 7   koi_fpflag_nt      9564 non-null   int64
 8   koi_fpflag_ss      9564 non-null   int64
 9   koi_fpflag_co      9564 non-null   int64
 10  koi_fpflag_ec      9564 non-null   int64
 11  koi_period         9564 non-null   float64
 12  koi_period_err1    9110 non-null   float64
 13  koi_period_err2    9110 non-null   float64
 14  koi_time0bk        9564 non-null   float64
 15  koi_time0bk_err1   9110 non-null   float64
 16  koi_time0bk_err2   9110 non-null   float64
 17  koi_impact         9201 non-null   float64
 18  koi_impact_err1    9110 non-null   float64
 19  koi_impact_err2    9110 non-null   float64
 20  koi_duration       9564 non-null   float64
 21  koi_duration_err1  9110 non-null   float64
 22  koi_duration_err2  9110 non-null   float64
 23  koi_depth          9201 non-null   float64
 24  koi_depth_err1     9110 non-null   float64
 25  koi_depth_err2     9110 non-null   float64
 26  koi_prad           9201 non-null   float64
 27  koi_prad_err1      9201 non-null   float64
 28  koi_prad_err2      9201 non-null   float64
 29  koi_teq            9201 non-null   float64
 30  koi_teq_err1       0 non-null      float64
 31  koi_teq_err2       0 non-null      float64
 32  koi_insol          9243 non-null   float64
 33  koi_insol_err1     9243 non-null   float64
 34  koi_insol_err2     9243 non-null   float64
 35  koi_model_snr      9201 non-null   float64
 36  koi_tce_plnt_num   9218 non-null   float64
 37  koi_tce_delivname  9218 non-null   object
 38  koi_steff          9201 non-null   float64
 39  koi_steff_err1     9096 non-null   float64
 40  koi_steff_err2     9081 non-null   float64
 41  koi_slogg          9201 non-null   float64
 42  koi_slogg_err1     9096 non-null   float64
 43  koi_slogg_err2     9096 non-null   float64
 44  koi_srad           9201 non-null   float64
 45  koi_srad_err1      9096 non-null   float64
 46  koi_srad_err2      9096 non-null   float64
 47  ra                 9564 non-null   float64
 48  dec                9564 non-null   float64
 49  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(6), object(5)
memory usage: 3.6+ MB
   rowid     kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0      1  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE
1      2  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE
2      3  10811496  K00753.01           NaN  FALSE POSITIVE   FALSE POSITIVE
3      4  10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE
4      5  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE

   koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  ...  \
0      1.000              0              0              0  ...
1      0.969              0              0              0  ...
2      0.000              0              1              0  ...
3      0.000              0              1              0  ...
4      1.000              0              0              0  ...

   koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0           -81.0      4.467           0.064          -0.096     0.927
1           -81.0      4.467           0.064          -0.096     0.927
2          -176.0      4.544           0.044          -0.176     0.868
3          -174.0      4.564           0.053          -0.168     0.791
4          -211.0      4.438           0.070          -0.210     1.046

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag
0          0.105         -0.061  291.93423  48.141651      15.347
1          0.105         -0.061  291.93423  48.141651      15.347
2          0.233         -0.078  297.00482  48.134129      15.436
3          0.201         -0.067  285.53461  48.285210      15.597
4          0.334         -0.133  288.75488  48.226200      15.509

[5 rows x 50 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              9564 non-null   int64
 1   kepid              9564 non-null   int64
 2   kepoi_name         9564 non-null   object
 3   kepler_name        2294 non-null   object
 4   koi_disposition    9564 non-null   object
 5   koi_pdisposition   9564 non-null   object
 6   koi_score          8054 non-null   float64
 7   koi_fpflag_nt      9564 non-null   int64
 8   koi_fpflag_ss      9564 non-null   int64
 9   koi_fpflag_co      9564 non-null   int64
 10  koi_fpflag_ec      9564 non-null   int64
 11  koi_period         9564 non-null   float64
 12  koi_period_err1    9110 non-null   float64
 13  koi_period_err2    9110 non-null   float64
 14  koi_time0bk        9564 non-null   float64
 15  koi_time0bk_err1   9110 non-null   float64
 16  koi_time0bk_err2   9110 non-null   float64
 17  koi_impact         9201 non-null   float64
 18  koi_impact_err1    9110 non-null   float64
 19  koi_impact_err2    9110 non-null   float64
 20  koi_duration       9564 non-null   float64
 21  koi_duration_err1  9110 non-null   float64
 22  koi_duration_err2  9110 non-null   float64
 23  koi_depth          9201 non-null   float64
 24  koi_depth_err1     9110 non-null   float64
 25  koi_depth_err2     9110 non-null   float64
 26  koi_prad           9201 non-null   float64
 27  koi_prad_err1      9201 non-null   float64
 28  koi_prad_err2      9201 non-null   float64
 29  koi_teq            9201 non-null   float64
 30  koi_teq_err1       0 non-null      float64
 31  koi_teq_err2       0 non-null      float64
 32  koi_insol          9243 non-null   float64
 33  koi_insol_err1     9243 non-null   float64
 34  koi_insol_err2     9243 non-null   float64
 35  koi_model_snr      9201 non-null   float64
 36  koi_tce_plnt_num   9218 non-null   float64
 37  koi_tce_delivname  9218 non-null   object
 38  koi_steff          9201 non-null   float64
 39  koi_steff_err1     9096 non-null   float64
 40  koi_steff_err2     9081 non-null   float64
 41  koi_slogg          9201 non-null   float64
 42  koi_slogg_err1     9096 non-null   float64
 43  koi_slogg_err2     9096 non-null   float64
 44  koi_srad           9201 non-null   float64
 45  koi_srad_err1      9096 non-null   float64
 46  koi_srad_err2      9096 non-null   float64
 47  ra                 9564 non-null   float64
 48  dec                9564 non-null   float64
 49  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(6), object(5)
memory usage: 3.6+ MB
None
             rowid         kepid    koi_score  koi_fpflag_nt  koi_fpflag_ss  \
count  9564.000000  9.564000e+03  8054.000000    9564.000000    9564.000000
mean   4782.500000  7.690628e+06     0.480829       0.188206       0.231598
std    2761.033321  2.653459e+06     0.476928       0.390897       0.421875
min       1.000000  7.574500e+05     0.000000       0.000000       0.000000
25%    2391.750000  5.556034e+06     0.000000       0.000000       0.000000
50%    4782.500000  7.906892e+06     0.334000       0.000000       0.000000
75%    7173.250000  9.873066e+06     0.998000       0.000000       0.000000
max    9564.000000  1.293514e+07     1.000000       1.000000       1.000000

       koi_fpflag_co  koi_fpflag_ec     koi_period  koi_period_err1  \
count    9564.000000    9564.000000    9564.000000      9110.000000
mean        0.194898       0.120033      75.671358         0.002148
std         0.396143       0.325018    1334.744046         0.008236
min         0.000000       0.000000       0.241843         0.000000
25%         0.000000       0.000000       2.733684         0.000005
50%         0.000000       0.000000       9.752831         0.000035
75%         0.000000       0.000000      40.715178         0.000276
max         1.000000       1.000000  129995.778400         0.172500

       koi_period_err2  ...  koi_steff_err2    koi_slogg  koi_slogg_err1  \
count      9110.000000  ...     9081.000000  9201.000000     9096.000000
mean         -0.002148  ...     -162.265059     4.310157        0.120738
std           0.008236  ...       72.746348     0.432606        0.132837
min          -0.172500  ...    -1762.000000     0.047000        0.000000
25%          -0.000276  ...     -198.000000     4.218000        0.042000
50%          -0.000035  ...     -160.000000     4.438000        0.070000
75%          -0.000005  ...     -114.000000     4.543000        0.149000
max           0.000000  ...        0.000000     5.364000        1.472000

       koi_slogg_err2     koi_srad  koi_srad_err1  koi_srad_err2           ra  \
count     9096.000000  9201.000000    9096.000000    9096.000000  9564.000000
mean        -0.143161     1.728712       0.362292      -0.394806   292.060163
std          0.085477     6.127185       0.930870       2.168213     4.766657
min         -1.207000     0.109000       0.000000    -116.137000   279.852720
25%         -0.196000     0.829000       0.129000      -0.250000   288.660770
50%         -0.128000     1.000000       0.251000      -0.111000   292.261125
75%         -0.088000     1.345000       0.364000      -0.069000   295.859160
max          0.000000   229.908000      33.091000       0.000000   301.720760

               dec   koi_kepmag
count  9564.000000  9563.000000
mean     43.810433    14.264606
std       3.601243     1.385448
min      36.577381     6.966000
25%      40.777173    13.440000
50%      43.677504    14.520000
75%      46.714611    15.322000
max      52.336010    20.003000

[8 rows x 45 columns]
(9564, 50)
Column names:

rowid
kepid
kepoi_name
kepler_name
koi_disposition
koi_pdisposition
koi_score
koi_fpflag_nt
koi_fpflag_ss
koi_fpflag_co
koi_fpflag_ec
koi_period
koi_period_err1
koi_period_err2
koi_time0bk
koi_time0bk_err1
koi_time0bk_err2
koi_impact
koi_impact_err1
koi_impact_err2
koi_duration
koi_duration_err1
koi_duration_err2
koi_depth
koi_depth_err1
koi_depth_err2
koi_prad
koi_prad_err1
koi_prad_err2
koi_teq
koi_teq_err1
koi_teq_err2
koi_insol
koi_insol_err1
koi_insol_err2
koi_model_snr
koi_tce_plnt_num
koi_tce_delivname
koi_steff
koi_steff_err1
koi_steff_err2
koi_slogg
koi_slogg_err1
koi_slogg_err2
koi_srad
koi_srad_err1
koi_srad_err2
ra
dec
koi_kepmag
--------TO FIND EMPTY COLUMNS--------
Completely empty columns:
['koi_teq_err1', 'koi_teq_err2']
Number of completely empty columns: 2
-----MISSING VALUES-----
rowid                   0
kepid                   0
kepoi_name              0
kepler_name          7270
koi_disposition         0
koi_pdisposition        0
koi_score            1510
koi_fpflag_nt           0
koi_fpflag_ss           0
koi_fpflag_co           0
koi_fpflag_ec           0
koi_period              0
koi_period_err1       454
koi_period_err2       454
koi_time0bk             0
koi_time0bk_err1      454
koi_time0bk_err2      454
koi_impact            363
koi_impact_err1       454
koi_impact_err2       454
koi_duration            0
koi_duration_err1     454
koi_duration_err2     454
koi_depth             363
koi_depth_err1        454
koi_depth_err2        454
koi_prad              363
koi_prad_err1         363
koi_prad_err2         363
koi_teq               363
koi_teq_err1         9564
koi_teq_err2         9564
koi_insol             321
koi_insol_err1        321
koi_insol_err2        321
koi_model_snr         363
koi_tce_plnt_num      346
koi_tce_delivname     346
koi_steff             363
koi_steff_err1        468
koi_steff_err2        483
koi_slogg             363
koi_slogg_err1        468
koi_slogg_err2        468
koi_srad              363
koi_srad_err1         468
koi_srad_err2         468
ra                      0
dec                     0
koi_kepmag              1
dtype: int64
------MISSING VALUES PERCENTAGE-------
rowid                  0.00
kepid                  0.00
kepoi_name             0.00
kepler_name           76.01
koi_disposition        0.00
koi_pdisposition       0.00
koi_score             15.79
koi_fpflag_nt          0.00
koi_fpflag_ss          0.00
koi_fpflag_co          0.00
koi_fpflag_ec          0.00
koi_period             0.00
koi_period_err1        4.75
koi_period_err2        4.75
koi_time0bk            0.00
koi_time0bk_err1       4.75
koi_time0bk_err2       4.75
koi_impact             3.80
koi_impact_err1        4.75
koi_impact_err2        4.75
koi_duration           0.00
koi_duration_err1      4.75
koi_duration_err2      4.75
koi_depth              3.80
koi_depth_err1         4.75
koi_depth_err2         4.75
koi_prad               3.80
koi_prad_err1          3.80
koi_prad_err2          3.80
koi_teq                3.80
koi_teq_err1         100.00
koi_teq_err2         100.00
koi_insol              3.36
koi_insol_err1         3.36
koi_insol_err2         3.36
koi_model_snr          3.80
koi_tce_plnt_num       3.62
koi_tce_delivname      3.62
koi_steff              3.80
koi_steff_err1         4.89
koi_steff_err2         5.05
koi_slogg              3.80
koi_slogg_err1         4.89
koi_slogg_err2         4.89
koi_srad               3.80
koi_srad_err1          4.89
koi_srad_err2          4.89
ra                     0.00
dec                    0.00
koi_kepmag             0.01
dtype: float64
------MISSING REPORT------
               Column  Missing Values  Missing Percentage
0               rowid               0                0.00
1               kepid               0                0.00
2          kepoi_name               0                0.00
3         kepler_name            7270               76.01
4     koi_disposition               0                0.00
5    koi_pdisposition               0                0.00
6           koi_score            1510               15.79
7       koi_fpflag_nt               0                0.00
8       koi_fpflag_ss               0                0.00
9       koi_fpflag_co               0                0.00
10      koi_fpflag_ec               0                0.00
11         koi_period               0                0.00
12    koi_period_err1             454                4.75
13    koi_period_err2             454                4.75
14        koi_time0bk               0                0.00
15   koi_time0bk_err1             454                4.75
16   koi_time0bk_err2             454                4.75
17         koi_impact             363                3.80
18    koi_impact_err1             454                4.75
19    koi_impact_err2             454                4.75
20       koi_duration               0                0.00
21  koi_duration_err1             454                4.75
22  koi_duration_err2             454                4.75
23          koi_depth             363                3.80
24     koi_depth_err1             454                4.75
25     koi_depth_err2             454                4.75
26           koi_prad             363                3.80
27      koi_prad_err1             363                3.80
28      koi_prad_err2             363                3.80
29            koi_teq             363                3.80
30       koi_teq_err1            9564              100.00
31       koi_teq_err2            9564              100.00
32          koi_insol             321                3.36
33     koi_insol_err1             321                3.36
34     koi_insol_err2             321                3.36
35      koi_model_snr             363                3.80
36   koi_tce_plnt_num             346                3.62
37  koi_tce_delivname             346                3.62
38          koi_steff             363                3.80
39     koi_steff_err1             468                4.89
40     koi_steff_err2             483                5.05
41          koi_slogg             363                3.80
42     koi_slogg_err1             468                4.89
43     koi_slogg_err2             468                4.89
44           koi_srad             363                3.80
45      koi_srad_err1             468                4.89
46      koi_srad_err2             468                4.89
47                 ra               0                0.00
48                dec               0                0.00
49         koi_kepmag               1                0.01
               Column  Missing Values  Missing Percentage
31       koi_teq_err2            9564              100.00
30       koi_teq_err1            9564              100.00
3         kepler_name            7270               76.01
6           koi_score            1510               15.79
40     koi_steff_err2             483                5.05
46      koi_srad_err2             468                4.89
45      koi_srad_err1             468                4.89
43     koi_slogg_err2             468                4.89
42     koi_slogg_err1             468                4.89
39     koi_steff_err1             468                4.89
25     koi_depth_err2             454                4.75
16   koi_time0bk_err2             454                4.75
22  koi_duration_err2             454                4.75
21  koi_duration_err1             454                4.75
19    koi_impact_err2             454                4.75
18    koi_impact_err1             454                4.75
12    koi_period_err1             454                4.75
15   koi_time0bk_err1             454                4.75
13    koi_period_err2             454                4.75
24     koi_depth_err1             454                4.75
28      koi_prad_err2             363                3.80
29            koi_teq             363                3.80
27      koi_prad_err1             363                3.80
26           koi_prad             363                3.80
17         koi_impact             363                3.80
23          koi_depth             363                3.80
35      koi_model_snr             363                3.80
38          koi_steff             363                3.80
41          koi_slogg             363                3.80
44           koi_srad             363                3.80
36   koi_tce_plnt_num             346                3.62
37  koi_tce_delivname             346                3.62
32          koi_insol             321                3.36
33     koi_insol_err1             321                3.36
34     koi_insol_err2             321                3.36
49         koi_kepmag               1                0.01
1               kepid               0                0.00
20       koi_duration               0                0.00
14        koi_time0bk               0                0.00
11         koi_period               0                0.00
10      koi_fpflag_ec               0                0.00
9       koi_fpflag_co               0                0.00
8       koi_fpflag_ss               0                0.00
7       koi_fpflag_nt               0                0.00
5    koi_pdisposition               0                0.00
4     koi_disposition               0                0.00
2          kepoi_name               0                0.00
47                 ra               0                0.00
48                dec               0                0.00
0               rowid               0                0.00
-----DUPLICATE ROWS------
Number of duplicate rows: 0
No duplicate rows found.
Duplicate KOI names: 0
koi_disposition
FALSE POSITIVE    5023
CONFIRMED         2293
CANDIDATE         2248
Name: count, dtype: int64
-----Numerical columns-----
Number of numerical columns: 45

Numerical columns:
rowid
kepid
koi_score
koi_fpflag_nt
koi_fpflag_ss
koi_fpflag_co
koi_fpflag_ec
koi_period
koi_period_err1

        Column Data Type Category  Missing Values  Missing %
3  kepler_name    object       ID            7270      76.01

-------------Low missing columns-----------
Columns with less than 50% missing values:

               Column Data Type     Category  Missing Values  Missing %
6           koi_score   float64    Numerical            1510      15.79
12    koi_period_err1   float64    Numerical             454       4.75
13    koi_period_err2   float64    Numerical             454       4.75
15   koi_time0bk_err1   float64    Numerical             454       4.75
16   koi_time0bk_err2   float64    Numerical             454       4.75
17         koi_impact   float64    Numerical             363       3.80
18    koi_impact_err1   float64    Numerical             454       4.75
19    koi_impact_err2   float64    Numerical             454       4.75
21  koi_duration_err1   float64    Numerical             454       4.75
22  koi_duration_err2   float64    Numerical             454       4.75
23          koi_depth   float64    Numerical             363       3.80
24     koi_depth_err1   float64    Numerical             454       4.75
25     koi_depth_err2   float64    Numerical             454       4.75
26           koi_prad   float64    Numerical             363       3.80
27      koi_prad_err1   float64    Numerical             363       3.80
28      koi_prad_err2   float64    Numerical             363       3.80
29            koi_teq   float64    Numerical             363       3.80
30          koi_insol   float64    Numerical             321       3.36
31     koi_insol_err1   float64    Numerical             321       3.36
32     koi_insol_err2   float64    Numerical             321       3.36
33      koi_model_snr   float64    Numerical             363       3.80
34   koi_tce_plnt_num   float64    Numerical             346       3.62
35  koi_tce_delivname    object  Categorical             346       3.62
36          koi_steff   float64    Numerical             363       3.80
37     koi_steff_err1   float64    Numerical             468       4.89
38     koi_steff_err2   float64    Numerical             483       5.05
39          koi_slogg   float64    Numerical             363       3.80
40     koi_slogg_err1   float64    Numerical             468       4.89
41     koi_slogg_err2   float64    Numerical             468       4.89
42           koi_srad   float64    Numerical             363       3.80
43      koi_srad_err1   float64    Numerical             468       4.89
44      koi_srad_err2   float64    Numerical             468       4.89
47         koi_kepmag   float64    Numerical               1       0.01

----------------------------
Column classification saved successfully.


------Data dict-----------
               Column Data Type
0               rowid     int64
1               kepid     int64
2          kepoi_name    object
3         kepler_name    object
4     koi_disposition    object
5    koi_pdisposition    object
6           koi_score   float64
7       koi_fpflag_nt     int64
8       koi_fpflag_ss     int64
9       koi_fpflag_co     int64
10      koi_fpflag_ec     int64
11         koi_period   float64
12    koi_period_err1   float64
13    koi_period_err2   float64
14        koi_time0bk   float64
15   koi_time0bk_err1   float64
16   koi_time0bk_err2   float64
17         koi_impact   float64
18    koi_impact_err1   float64
19    koi_impact_err2   float64
20       koi_duration   float64
21  koi_duration_err1   float64
22  koi_duration_err2   float64
23          koi_depth   float64
24     koi_depth_err1   float64
25     koi_depth_err2   float64
26           koi_prad   float64
27      koi_prad_err1   float64
28      koi_prad_err2   float64
29            koi_teq   float64
30          koi_insol   float64
31     koi_insol_err1   float64
32     koi_insol_err2   float64
33      koi_model_snr   float64
34   koi_tce_plnt_num   float64
35  koi_tce_delivname    object
36          koi_steff   float64
37     koi_steff_err1   float64
38     koi_steff_err2   float64
39          koi_slogg   float64
40     koi_slogg_err1   float64
41     koi_slogg_err2   float64
42           koi_srad   float64
43      koi_srad_err1   float64
44      koi_srad_err2   float64
45                 ra   float64
46                dec   float64
47         koi_kepmag   float64

------After catergory added in data dic-----------
               Column Data Type     Category
0               rowid     int64    Numerical
1               kepid     int64           ID
2          kepoi_name    object           ID
3         kepler_name    object           ID
4     koi_disposition    object       Target
5    koi_pdisposition    object  Categorical
6           koi_score   float64    Numerical
7       koi_fpflag_nt     int64    Numerical
8       koi_fpflag_ss     int64    Numerical
9       koi_fpflag_co     int64    Numerical
10      koi_fpflag_ec     int64    Numerical
11         koi_period   float64    Numerical
12    koi_period_err1   float64    Numerical
13    koi_period_err2   float64    Numerical
14        koi_time0bk   float64    Numerical
15   koi_time0bk_err1   float64    Numerical
16   koi_time0bk_err2   float64    Numerical
17         koi_impact   float64    Numerical
18    koi_impact_err1   float64    Numerical
19    koi_impact_err2   float64    Numerical
20       koi_duration   float64    Numerical
21  koi_duration_err1   float64    Numerical
22  koi_duration_err2   float64    Numerical
23          koi_depth   float64    Numerical
24     koi_depth_err1   float64    Numerical
25     koi_depth_err2   float64    Numerical
26           koi_prad   float64    Numerical
27      koi_prad_err1   float64    Numerical
28      koi_prad_err2   float64    Numerical
29            koi_teq   float64    Numerical
30          koi_insol   float64    Numerical
31     koi_insol_err1   float64    Numerical
32     koi_insol_err2   float64    Numerical
33      koi_model_snr   float64    Numerical
34   koi_tce_plnt_num   float64    Numerical
35  koi_tce_delivname    object  Categorical
36          koi_steff   float64    Numerical
37     koi_steff_err1   float64    Numerical
38     koi_steff_err2   float64    Numerical
39          koi_slogg   float64    Numerical
40     koi_slogg_err1   float64    Numerical
41     koi_slogg_err2   float64    Numerical
42           koi_srad   float64    Numerical
43      koi_srad_err1   float64    Numerical
44      koi_srad_err2   float64    Numerical
45                 ra   float64    Numerical
46                dec   float64    Numerical
47         koi_kepmag   float64    Numerical

--------------------------------------------------------
               Column Data Type     Category  Missing Values  Missing %
0               rowid     int64    Numerical               0       0.00
1               kepid     int64           ID               0       0.00
2          kepoi_name    object           ID               0       0.00
3         kepler_name    object           ID            7270      76.01
4     koi_disposition    object       Target               0       0.00
5    koi_pdisposition    object  Categorical               0       0.00
6           koi_score   float64    Numerical            1510      15.79
7       koi_fpflag_nt     int64    Numerical               0       0.00
8       koi_fpflag_ss     int64    Numerical               0       0.00
9       koi_fpflag_co     int64    Numerical               0       0.00
10      koi_fpflag_ec     int64    Numerical               0       0.00
11         koi_period   float64    Numerical               0       0.00
12    koi_period_err1   float64    Numerical             454       4.75
13    koi_period_err2   float64    Numerical             454       4.75
14        koi_time0bk   float64    Numerical               0       0.00
15   koi_time0bk_err1   float64    Numerical             454       4.75
16   koi_time0bk_err2   float64    Numerical             454       4.75
17         koi_impact   float64    Numerical             363       3.80
18    koi_impact_err1   float64    Numerical             454       4.75
19    koi_impact_err2   float64    Numerical             454       4.75
20       koi_duration   float64    Numerical               0       0.00
21  koi_duration_err1   float64    Numerical             454       4.75
22  koi_duration_err2   float64    Numerical             454       4.75
23          koi_depth   float64    Numerical             363       3.80
24     koi_depth_err1   float64    Numerical             454       4.75
25     koi_depth_err2   float64    Numerical             454       4.75
26           koi_prad   float64    Numerical             363       3.80
27      koi_prad_err1   float64    Numerical             363       3.80
28      koi_prad_err2   float64    Numerical             363       3.80
29            koi_teq   float64    Numerical             363       3.80
30          koi_insol   float64    Numerical             321       3.36
31     koi_insol_err1   float64    Numerical             321       3.36
32     koi_insol_err2   float64    Numerical             321       3.36
33      koi_model_snr   float64    Numerical             363       3.80
34   koi_tce_plnt_num   float64    Numerical             346       3.62
35  koi_tce_delivname    object  Categorical             346       3.62
36          koi_steff   float64    Numerical             363       3.80
37     koi_steff_err1   float64    Numerical             468       4.89
38     koi_steff_err2   float64    Numerical             483       5.05
39          koi_slogg   float64    Numerical             363       3.80
40     koi_slogg_err1   float64    Numerical             468       4.89
41     koi_slogg_err2   float64    Numerical             468       4.89
42           koi_srad   float64    Numerical             363       3.80
43      koi_srad_err1   float64    Numerical             468       4.89
44      koi_srad_err2   float64    Numerical             468       4.89
45                 ra   float64    Numerical               0       0.00
46                dec   float64    Numerical               0       0.00
47         koi_kepmag   float64    Numerical               1       0.01

------------------------------------------------------------------
               Column Data Type     Category  Missing Values  Missing %  \
0               rowid     int64    Numerical               0       0.00
1               kepid     int64           ID               0       0.00
2          kepoi_name    object           ID               0       0.00
3         kepler_name    object           ID            7270      76.01
4     koi_disposition    object       Target               0       0.00
5    koi_pdisposition    object  Categorical               0       0.00
6           koi_score   float64    Numerical            1510      15.79
7       koi_fpflag_nt     int64    Numerical               0       0.00
8       koi_fpflag_ss     int64    Numerical               0       0.00
9       koi_fpflag_co     int64    Numerical               0       0.00
10      koi_fpflag_ec     int64    Numerical               0       0.00
11         koi_period   float64    Numerical               0       0.00
12    koi_period_err1   float64    Numerical             454       4.75
13    koi_period_err2   float64    Numerical             454       4.75
14        koi_time0bk   float64    Numerical               0       0.00
15   koi_time0bk_err1   float64    Numerical             454       4.75
16   koi_time0bk_err2   float64    Numerical             454       4.75
17         koi_impact   float64    Numerical             363       3.80
18    koi_impact_err1   float64    Numerical             454       4.75
19    koi_impact_err2   float64    Numerical             454       4.75
20       koi_duration   float64    Numerical               0       0.00
21  koi_duration_err1   float64    Numerical             454       4.75
22  koi_duration_err2   float64    Numerical             454       4.75
23          koi_depth   float64    Numerical             363       3.80
24     koi_depth_err1   float64    Numerical             454       4.75
25     koi_depth_err2   float64    Numerical             454       4.75
26           koi_prad   float64    Numerical             363       3.80
27      koi_prad_err1   float64    Numerical             363       3.80
28      koi_prad_err2   float64    Numerical             363       3.80
29            koi_teq   float64    Numerical             363       3.80
30          koi_insol   float64    Numerical             321       3.36
31     koi_insol_err1   float64    Numerical             321       3.36
32     koi_insol_err2   float64    Numerical             321       3.36
33      koi_model_snr   float64    Numerical             363       3.80
34   koi_tce_plnt_num   float64    Numerical             346       3.62
35  koi_tce_delivname    object  Categorical             346       3.62
36          koi_steff   float64    Numerical             363       3.80
37     koi_steff_err1   float64    Numerical             468       4.89
38     koi_steff_err2   float64    Numerical             483       5.05
39          koi_slogg   float64    Numerical             363       3.80
40     koi_slogg_err1   float64    Numerical             468       4.89
41     koi_slogg_err2   float64    Numerical             468       4.89
42           koi_srad   float64    Numerical             363       3.80
43      koi_srad_err1   float64    Numerical             468       4.89
44      koi_srad_err2   float64    Numerical             468       4.89
45                 ra   float64    Numerical               0       0.00
46                dec   float64    Numerical               0       0.00
47         koi_kepmag   float64    Numerical               1       0.01

                                              Meaning
0                                                 NaN
1                        Kepler identification number
2                      Kepler Object of Interest name
3   Official Kepler name assigned to a confirmed p...
4      Final classification/disposition of the object
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                    Orbital period of the candidate
12                Upper uncertainty of orbital period
13                Lower uncertainty of orbital period
14                              Transit midpoint time
15              Upper uncertainty of transit midpoint
16              Lower uncertainty of transit midpoint
17                    Impact parameter of the transit
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                      Transit depth
24                                                NaN
25                                                NaN
26                         Estimated planetary radius
27                                                NaN
28                                                NaN
29                  Estimated equilibrium temperature
30                    Estimated incident stellar flux
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36             Effective temperature of the host star
37                                                NaN
38                                                NaN
39                   Surface gravity of the host star
40                                                NaN
41                                                NaN
42                            Radius of the host star
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN

-----------------------------------------
Columns still needing documentation:
['rowid', 'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec', 'koi_impact_err1', 'koi_impact_err2', 'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth_err1', 'koi_depth_err2', 'koi_prad_err1', 'koi_prad_err2', 'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num', 'koi_tce_delivname', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag']

------------------------------------------
               Column Data Type     Category  Missing Values  Missing %  \
0               rowid     int64    Numerical               0       0.00
1               kepid     int64           ID               0       0.00
2          kepoi_name    object           ID               0       0.00
3         kepler_name    object           ID            7270      76.01
4     koi_disposition    object       Target               0       0.00
5    koi_pdisposition    object  Categorical               0       0.00
6           koi_score   float64    Numerical            1510      15.79
7       koi_fpflag_nt     int64    Numerical               0       0.00
8       koi_fpflag_ss     int64    Numerical               0       0.00
9       koi_fpflag_co     int64    Numerical               0       0.00
10      koi_fpflag_ec     int64    Numerical               0       0.00
11         koi_period   float64    Numerical               0       0.00
12    koi_period_err1   float64    Numerical             454       4.75
13    koi_period_err2   float64    Numerical             454       4.75
14        koi_time0bk   float64    Numerical               0       0.00
15   koi_time0bk_err1   float64    Numerical             454       4.75
16   koi_time0bk_err2   float64    Numerical             454       4.75
17         koi_impact   float64    Numerical             363       3.80
18    koi_impact_err1   float64    Numerical             454       4.75
19    koi_impact_err2   float64    Numerical             454       4.75
20       koi_duration   float64    Numerical               0       0.00
21  koi_duration_err1   float64    Numerical             454       4.75
22  koi_duration_err2   float64    Numerical             454       4.75
23          koi_depth   float64    Numerical             363       3.80
24     koi_depth_err1   float64    Numerical             454       4.75
25     koi_depth_err2   float64    Numerical             454       4.75
26           koi_prad   float64    Numerical             363       3.80
27      koi_prad_err1   float64    Numerical             363       3.80
28      koi_prad_err2   float64    Numerical             363       3.80
29            koi_teq   float64    Numerical             363       3.80
30          koi_insol   float64    Numerical             321       3.36
31     koi_insol_err1   float64    Numerical             321       3.36
32     koi_insol_err2   float64    Numerical             321       3.36
33      koi_model_snr   float64    Numerical             363       3.80
34   koi_tce_plnt_num   float64    Numerical             346       3.62
35  koi_tce_delivname    object  Categorical             346       3.62
36          koi_steff   float64    Numerical             363       3.80
37     koi_steff_err1   float64    Numerical             468       4.89
38     koi_steff_err2   float64    Numerical             483       5.05
39          koi_slogg   float64    Numerical             363       3.80
40     koi_slogg_err1   float64    Numerical             468       4.89
41     koi_slogg_err2   float64    Numerical             468       4.89
42           koi_srad   float64    Numerical             363       3.80
43      koi_srad_err1   float64    Numerical             468       4.89
44      koi_srad_err2   float64    Numerical             468       4.89
45                 ra   float64    Numerical               0       0.00
46                dec   float64    Numerical               0       0.00
47         koi_kepmag   float64    Numerical               1       0.01

                                              Meaning              ML Role
0                                                 NaN    Potential feature
1                        Kepler identification number  Do not use directly
2                      Kepler Object of Interest name  Do not use directly
3   Official Kepler name assigned to a confirmed p...  Do not use directly
4      Final classification/disposition of the object               Target
5                                                 NaN    Potential feature
6                                                 NaN    Potential feature
7                                                 NaN    Potential feature
8                                                 NaN    Potential feature
9                                                 NaN    Potential feature
10                                                NaN    Potential feature
11                    Orbital period of the candidate    Potential feature
12                Upper uncertainty of orbital period    Potential feature
13                Lower uncertainty of orbital period    Potential feature
14                              Transit midpoint time    Potential feature
15              Upper uncertainty of transit midpoint    Potential feature
16              Lower uncertainty of transit midpoint    Potential feature
17                    Impact parameter of the transit    Potential feature
18                                                NaN    Potential feature
19                                                NaN    Potential feature
20                                                NaN    Potential feature
21                                                NaN    Potential feature
22                                                NaN    Potential feature
23                                      Transit depth    Potential feature
24                                                NaN    Potential feature
25                                                NaN    Potential feature

               Column  Missing Values  Missing %
3         kepler_name            7270      76.01
6           koi_score            1510      15.79
38     koi_steff_err2             483       5.05
43      koi_srad_err1             468       4.89
40     koi_slogg_err1             468       4.89
41     koi_slogg_err2             468       4.89
37     koi_steff_err1             468       4.89
44      koi_srad_err2             468       4.89
18    koi_impact_err1             454       4.75
19    koi_impact_err2             454       4.75
21  koi_duration_err1             454       4.75
24     koi_depth_err1             454       4.75
25     koi_depth_err2             454       4.75
16   koi_time0bk_err2             454       4.75
15   koi_time0bk_err1             454       4.75
13    koi_period_err2             454       4.75
12    koi_period_err1             454       4.75
22  koi_duration_err2             454       4.75
36          koi_steff             363       3.80
42           koi_srad             363       3.80
39          koi_slogg             363       3.80
29            koi_teq             363       3.80
33      koi_model_snr             363       3.80
28      koi_prad_err2             363       3.80
27      koi_prad_err1             363       3.80
26           koi_prad             363       3.80
23          koi_depth             363       3.80
17         koi_impact             363       3.80
34   koi_tce_plnt_num             346       3.62
35  koi_tce_delivname             346       3.62
32     koi_insol_err2             321       3.36
31     koi_insol_err1             321       3.36
30          koi_insol             321       3.36
47         koi_kepmag               1       0.01

------------------------------------------

,Column,Missing Values,Missing %,Meaning,Category
0,kepler_name,7270,76.01,Official Kepler name assigned to a confirmed p...,ID
1,koi_score,1510,15.79,NaN,Numerical
2,koi_steff_err2,483,5.05,NaN,Numerical
3,koi_srad_err1,468,4.89,NaN,Numerical
4,koi_slogg_err1,468,4.89,NaN,Numerical
5,koi_slogg_err2,468,4.89,NaN,Numerical
6,koi_steff_err1,468,4.89,NaN,Numerical
7,koi_srad_err2,468,4.89,NaN,Numerical
8,koi_impact_err1,454,4.75,NaN,Numerical
9,koi_impact_err2,454,4.75,NaN,Numerical
10,koi_duration_err1,454,4.75,NaN,Numerical
11,koi_depth_err1,454,4.75,NaN,Numerical
12,koi_depth_err2,454,4.75,NaN,Numerical
13,koi_time0bk_err2,454,4.75,Lower uncertainty of transit midpoint,Numerical
14,koi_time0bk_err1,454,4.75,Upper uncertainty of transit midpoint,Numerical
15,koi_period_err2,454,4.75,Lower uncertainty of orbital period,Numerical
16,koi_period_err1,454,4.75,Upper uncertainty of orbital period,Numerical
17,koi_duration_err2,454,4.75,NaN,Numerical
18,koi_steff,363,3.80,Effective temperature of the host star,Numerical
19,koi_srad,363,3.80,Radius of the host star,Numerical
20,koi_slogg,363,3.80,Surface gravity of the host star,Numerical
21,koi_teq,363,3.80,Estimated equilibrium temperature,Numerical
22,koi_model_snr,363,3.80,NaN,Numerical
23,koi_prad_err2,363,3.80,NaN,Numerical
24,koi_prad_err1,363,3.80,NaN,Numerical
25,koi_prad,363,3.80,Estimated planetary radius,Numerical
26,koi_depth,363,3.80,Transit depth,Numerical
27,koi_impact,363,3.80,Impact parameter of the transit,Numerical
28,koi_tce_plnt_num,346,3.62,NaN,Numerical
29,koi_tce_delivname,346,3.62,NaN,Categorical
30,koi_insol_err2,321,3.36,NaN,Numerical
31,koi_insol_err1,321,3.36,NaN,Numerical
32,koi_insol,321,3.36,Estimated incident stellar flux,Numerical
33,koi_kepmag,1,0.01,NaN,Numerical

-----------Missing level and decision---------------

,Column,Missing Values,Missing %,Meaning,Category,Missing Level
0,kepler_name,7270,76.01,Official Kepler name assigned to a confirmed p...,ID,High
1,koi_score,1510,15.79,NaN,Numerical,Low
2,koi_steff_err2,483,5.05,NaN,Numerical,Low
3,koi_srad_err1,468,4.89,NaN,Numerical,Low
4,koi_slogg_err1,468,4.89,NaN,Numerical,Low
5,koi_slogg_err2,468,4.89,NaN,Numerical,Low
6,koi_steff_err1,468,4.89,NaN,Numerical,Low
7,koi_srad_err2,468,4.89,NaN,Numerical,Low
8,koi_impact_err1,454,4.75,NaN,Numerical,Low
9,koi_impact_err2,454,4.75,NaN,Numerical,Low
10,koi_duration_err1,454,4.75,NaN,Numerical,Low
11,koi_depth_err1,454,4.75,NaN,Numerical,Low
12,koi_depth_err2,454,4.75,NaN,Numerical,Low
13,koi_time0bk_err2,454,4.75,Lower uncertainty of transit midpoint,Numerical,Low
14,koi_time0bk_err1,454,4.75,Upper uncertainty of transit midpoint,Numerical,Low
15,koi_period_err2,454,4.75,Lower uncertainty of orbital period,Numerical,Low
16,koi_period_err1,454,4.75,Upper uncertainty of orbital period,Numerical,Low
17,koi_duration_err2,454,4.75,NaN,Numerical,Low
18,koi_steff,363,3.80,Effective temperature of the host star,Numerical,Low
19,koi_srad,363,3.80,Radius of the host star,Numerical,Low
20,koi_slogg,363,3.80,Surface gravity of the host star,Numerical,Low
21,koi_teq,363,3.80,Estimated equilibrium temperature,Numerical,Low
22,koi_model_snr,363,3.80,NaN,Numerical,Low
23,koi_prad_err2,363,3.80,NaN,Numerical,Low
24,koi_prad_err1,363,3.80,NaN,Numerical,Low
25,koi_prad,363,3.80,Estimated planetary radius,Numerical,Low
26,koi_depth,363,3.80,Transit depth,Numerical,Low
27,koi_impact,363,3.80,Impact parameter of the transit,Numerical,Low
28,koi_tce_plnt_num,346,3.62,NaN,Numerical,Low
29,koi_tce_delivname,346,3.62,NaN,Categorical,Low
30,koi_insol_err2,321,3.36,NaN,Numerical,Low
31,koi_insol_err1,321,3.36,NaN,Numerical,Low
32,koi_insol,321,3.36,Estimated incident stellar flux,Numerical,Low
33,koi_kepmag,1,0.01,NaN,Numerical,Low

---------------------------------------------------------

,Column,Missing %,Meaning,Category,Decision
0,kepler_name,76.01,Official Kepler name assigned to a confirmed p...,ID,Review
1,koi_score,15.79,NaN,Numerical,Fill median
2,koi_steff_err2,5.05,NaN,Numerical,Fill median
3,koi_srad_err1,4.89,NaN,Numerical,Fill median
4,koi_slogg_err1,4.89,NaN,Numerical,Fill median
5,koi_slogg_err2,4.89,NaN,Numerical,Fill median
6,koi_steff_err1,4.89,NaN,Numerical,Fill median
7,koi_srad_err2,4.89,NaN,Numerical,Fill median
8,koi_impact_err1,4.75,NaN,Numerical,Fill median
9,koi_impact_err2,4.75,NaN,Numerical,Fill median
10,koi_duration_err1,4.75,NaN,Numerical,Fill median
11,koi_depth_err1,4.75,NaN,Numerical,Fill median
12,koi_depth_err2,4.75,NaN,Numerical,Fill median
13,koi_time0bk_err2,4.75,Lower uncertainty of transit midpoint,Numerical,Fill median
14,koi_time0bk_err1,4.75,Upper uncertainty of transit midpoint,Numerical,Fill median
15,koi_period_err2,4.75,Lower uncertainty of orbital period,Numerical,Fill median
16,koi_period_err1,4.75,Upper uncertainty of orbital period,Numerical,Fill median
17,koi_duration_err2,4.75,NaN,Numerical,Fill median
18,koi_steff,3.80,Effective temperature of the host star,Numerical,Fill median
19,koi_srad,3.80,Radius of the host star,Numerical,Fill median
20,koi_slogg,3.80,Surface gravity of the host star,Numerical,Fill median
21,koi_teq,3.80,Estimated equilibrium temperature,Numerical,Fill median
22,koi_model_snr,3.80,NaN,Numerical,Fill median
23,koi_prad_err2,3.80,NaN,Numerical,Fill median
24,koi_prad_err1,3.80,NaN,Numerical,Fill median
25,koi_prad,3.80,Estimated planetary radius,Numerical,Fill median
26,koi_depth,3.80,Transit depth,Numerical,Fill median
27,koi_impact,3.80,Impact parameter of the transit,Numerical,Fill median
28,koi_tce_plnt_num,3.62,NaN,Numerical,Fill median
29,koi_tce_delivname,3.62,NaN,Categorical,Fill mode
30,koi_insol_err2,3.36,NaN,Numerical,Fill median
31,koi_insol_err1,3.36,NaN,Numerical,Fill median
32,koi_insol,3.36,Estimated incident stellar flux,Numerical,Fill median
33,koi_kepmag,0.01,NaN,Numerical,Fill median

---------Saving Missing value decision in a csv file------------
Missing-value decisions saved successfully!

------Data cleaning--------
Columns to remove:
[]

------Dropping column-----------
Columns removed: 0

------------------------------------------
Numerical missing values filled.

-----------------------------------------
Categorical missing values filled.

------checking remaining missing values-------
Remaining missing values:
No missing values


-------Final comparision----------
Original dataset:
Rows: 9564
Columns: 50

Cleaned dataset:
Rows: 9564
Columns: 48

Total missing values after cleaning: 0

-----Saving the cleaned dataset---------
Cleaned dataset saved successfully!

-----------cleaning done---------------


------------ OUTLIER FLAG----------------------
Outlier flagging completed.

Total rows: 9564
Rows containing at least one outlier: 5245

Outlier Report:

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outlier Count
0,koi_period,2.733684,40.715178,37.981493,-54.238556,97.687418,1567
1,koi_duration,2.437750,6.276500,3.838750,-3.320375,12.034625,869
2,koi_depth,166.800000,1341.775000,1174.975000,-1595.662500,3104.237500,1834
3,koi_prad,1.430000,13.112500,11.682500,-16.093750,30.636250,1618
4,koi_teq,553.000000,1352.500000,799.500000,-646.250000,2551.750000,450
5,koi_insol,22.160000,806.797500,784.637500,-1154.796250,1983.753750,1509
6,koi_model_snr,12.300000,71.125000,58.825000,-75.937500,159.362500,1673
7,koi_steff,5333.000000,6099.000000,766.000000,4184.000000,7248.000000,595
8,koi_slogg,4.232750,4.539000,0.306250,3.773375,4.998375,734
9,koi_srad,0.835750,1.313000,0.477250,0.119875,2.028875,1074
10,koi_kepmag,13.440000,15.322000,1.882000,10.617000,18.145000,156

-------------------- HOST STAR analyze using kepid----------------------
Total observations: 9564
Unique host stars: 8214

Host-star observation counts:

     kepid  KOI_Count
0   757450          1
1   892772          1
2  1025986          1
3  1026032          1
4  1026957          1
5  1027438          1
6  1161345          1
7  1161949          1
8  1164301          1
9  1293031          1

Host stars with more than one observation: 938

Detailed host-star summary:

     kepid  KOI_Count  Confirmed  Candidate  False_Positive
0   757450          1          1          0               0
1   892772          1          0          0               1
2  1025986          1          0          0               1
3  1026032          1          0          0               1
4  1026957          1          0          1               0
5  1027438          1          0          0               1
6  1161345          1          0          1               0
7  1161949          1          0          0               1
8  1164301          1          0          0               1
9  1293031          1          0          0               1

Host stars with highest number of observations:

         kepid  KOI_Count  Confirmed  Candidate  False_Positive
7940  11968463          7          2          3               2
7574  11442793          7          6          1               0
6545  10187017          6          5          1               0
2970   6541920          6          6          0               0
7779  11709124          6          5          1               0
4345   8120608          5          5          0               0
1389   4852528          5          5          0               0
3445   7100673          5          4          1               0
1197   4571004          5          0          0               5
2702   6278762          5          5          0               0

------------------GROUP DATA BY HOST STAR------------------------
Host-star based splitting completed.

Original dataset:
Rows: 9564

Training dataset:
Rows: 7662
Unique host stars: 6571

Testing dataset:
Rows: 1902
Unique host stars: 1643

Host stars present in both datasets: 0
PASS: No host star is shared between train and test.
--------------- FINAL PREPARED DATASET_-----------------------
FINAL DATASET

1. DATASET SHAPE
Rows: 9564
Columns: 60

2. MISSING VALUES
Total missing values: 0
PASS: No missing values found.

3. DUPLICATE ROWS
Duplicate rows: 0
PASS: No duplicate rows found.

4. INFINITE VALUES
Infinite values: 0
PASS: No infinite values found.

5. TARGET DISTRIBUTION
koi_disposition
FALSE POSITIVE    5023
CONFIRMED         2293
CANDIDATE         2248
Name: count, dtype: int64

6. OUTLIER INFORMATION
Rows with at least one flagged outlier: 5245

7. HOST-STAR SPLIT VALIDATION
Common host stars between train and test: 0
PASS: Train and test host stars do not overlap.

-------------------------------------------------------------
FINAL VALIDATION: PASSED
---------------------------------------------------

---------- SHARING - PREPARED DATA---------------


-------------ALL FILES EXPORTED SUCCESSFULLY---------------------

Prepared Data Files:
1. prepared_data.csv
2. kepler_train_by_host.csv
3. kepler_test_by_host.csv


Report Files:
4. rep_host_star_summary.csv
5. rep_outlier_report.csv
6. rep_final_validation.csv


Member 1 data preparation work is completed.